version: "3"

x-dbenv: &dbenv
  DB_USER: "gosample2022_user"
  DB_PASSWORD: "gosample2022_password"
  DB_HOST: "mysql"
  DB_NAME: "gosample2022_development"
  DB_PORT: 3306

services:
  app:
    tty: true
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    ports:
      - 8080:8080
    volumes:
      - .:/go/src
    environment:
      ENV: "local"
      ROLLBAR_TOKEN: ${ROLLBAR_TOKEN}
      <<: *dbenv
    depends_on:
      - mysql
      - redis
      - kafka
      - localstack
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "5m"

  mysql:
    platform: linux/x86_64
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d/
    environment:
      <<: *dbenv
      MYSQL_ROOT_PASSWORD: root
      BIND-ADDRESS: 0.0.0.0
    command:
      [
          "mysqld",
          "--character-set-server=utf8mb4",
          "--collation-server=utf8mb4_bin",
      ]
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - "./data/redis:/data"
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/mongo:/data/db
  localstack:
    image: localstack/localstack
    restart: always
    ports:
      - 4566:4566
      - 4571:4571
      - 18080:8080
    environment:
      SERVICES: s3,sqs,kms
      DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /data/localstack
      DOCKER_HOST: unix:///var/run/docker.sock
      INIT_SCRIPTS_PATH: /docker-entrypoint-initaws.d
      KMS_PROVIDER: local-kms
    volumes:
      - "./data/localstack:/data/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker/localstack/docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./data/zookeeper/data:/var/lib/zookeeper/data
      - ./data/zookeeper/log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  maxwell:
    image: zendesk/maxwell
    depends_on:
      - kafka
      - mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysql
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      MAXWELL_OPTIONS: --kafka_topic=gosample2022_maxwell
