version: "3"

x-dbenv: &dbenv
  DB_USER: "gosample2022_user"
  DB_PASSWORD: "gosample2022_password"
  DB_HOST: "db"
  DB_NAME: "gosample2022_development"
  DB_PORT: 3306

services:
  app:
    tty: true
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    ports:
      - 8080:8080
    volumes:
      - .:/go/src
    environment:
      ENV: "development"
      ROLLBAR_TOKEN: ${ROLLBAR_TOKEN}
      <<: *dbenv
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "5m"

  db:
    tty: true
    platform: linux/x86_64
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./dbvolume:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      <<: *dbenv
      MYSQL_ROOT_PASSWORD: root
      BIND-ADDRESS: 0.0.0.0
    command:
      [
          "mysqld",
          "--character-set-server=utf8mb4",
          "--collation-server=utf8mb4_bin",
      ]
