env: development
app:
  service_name: github.com/ktakenaka/gosample2022
  port: 8080
  api: v1
  is_rollbar: false
db:
  write:
    user: writer
    password: writer_password
    host: db
    port: 3306
    db_name: gosample2022_development
  read:
    user: reader
    password: reader_password
    host: db
    port: 3306
    db_name: gosample2022_development
redis:
  url: redis://@redis:6379
  use_tls: false
mongo:
  url: mongodb://root:password@mongodb:27017
  db_name: gosample2022_development
rollbar:
  token: ${ROLLBAR_TOKEN}
