env: development
app:
  service_name: github.com/ktakenaka/gosample2022
  port: 8080
  api: v1
  is_rollbar: false
db:
  write:
    user: writer
    password: writer_password
    host: localhost
    port: 3306
    db_name: gosample2022_development
  read:
    user: reader
    password: reader_password
    host: localhost
    port: 3306
    db_name: gosample2022_development
redis:
  url: redis://@localhost:6379
  use_tls: false
mongo:
  url: mongodb://root:password@mongodb:27017
  db_name: gosample2022_development
kafka:
  address: localhost:9092
  topic_samples: gosample2022_dbserver.gosample2022_development.samples
  topic_transactions: gosample2022_dbserver.transaction
rollbar:
  token: ${ROLLBAR_TOKEN}
aws:
  id: gosample2022
  secret: gosample2022
  region: ap-northeast-1
  endpoint: http://localhost:4566
kms:
  master_key_id: alias/local-kms-key
