FROM golang:1.18beta1-alpine3.15

RUN apk update && apk upgrade && apk add --update alpine-sdk protoc git

# On local development (local), we just use 1 image for more convenience.
RUN go install github.com/volatiletech/sqlboiler/v4@latest &&\
  go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mysql@latest &&\
  go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26 &&\
  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

WORKDIR /go/src
