FROM golang:1.18

RUN apt-get update && apt-get install -y \
  protobuf-compiler \
  libprotobuf-dev

# On local development (local), we just use 1 image for more convenience.
RUN go install github.com/volatiletech/sqlboiler/v4@latest &&\
  go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mysql@latest &&\
  go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26 &&\
  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1 &&\
  go install golang.org/x/tools/cmd/goimports@latest

WORKDIR /go/src
