wipe     = true
no-tests = true
output   ="app/domain/models"

[mysql]
  dbname    = "gosample2022_development"
  host      = "mysql"
  port      = 3306
  user      = "reader"
  pass      = "reader_password"
  sslmode   = "false"
  blacklist = ["schema_migrations"]

[[types]]
  [types.match]
    type = "types.Decimal"
  [types.replace]
    type = "decimal.Decimal"
  [types.imports]
    third_party = ['"github.com/shopspring/decimal"']
