wipe     = true
no-tests = true
output   ="app/models"

[mysql]
  dbname    = "gosample2022_development"
  host      = "db"
  port      = 3306
  user      = "reader"
  pass      = "reader_password"
  sslmode   = "false"
  blacklist = ["schema_migrations"]
