// Code generated by SQLBoiler 4.9.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	OfficeUsers   string
	Offices       string
	OffsetSamples string
	SampleCopies  string
	Samples       string
	Users         string
}{
	OfficeUsers:   "office_users",
	Offices:       "offices",
	OffsetSamples: "offset_samples",
	SampleCopies:  "sample_copies",
	Samples:       "samples",
	Users:         "users",
}
