// Code generated by SQLBoiler 4.9.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Office is an object representing the database table.
type Office struct {
	ID   string `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name string `boil:"name" json:"name" toml:"name" yaml:"name"`

	R *officeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L officeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var OfficeColumns = struct {
	ID   string
	Name string
}{
	ID:   "id",
	Name: "name",
}

var OfficeTableColumns = struct {
	ID   string
	Name string
}{
	ID:   "offices.id",
	Name: "offices.name",
}

// Generated where

var OfficeWhere = struct {
	ID   whereHelperstring
	Name whereHelperstring
}{
	ID:   whereHelperstring{field: "`offices`.`id`"},
	Name: whereHelperstring{field: "`offices`.`name`"},
}

// OfficeRels is where relationship names are stored.
var OfficeRels = struct {
	OfficeUsers  string
	SampleCopies string
	Samples      string
	TreeSamples  string
}{
	OfficeUsers:  "OfficeUsers",
	SampleCopies: "SampleCopies",
	Samples:      "Samples",
	TreeSamples:  "TreeSamples",
}

// officeR is where relationships are stored.
type officeR struct {
	OfficeUsers  OfficeUserSlice `boil:"OfficeUsers" json:"OfficeUsers" toml:"OfficeUsers" yaml:"OfficeUsers"`
	SampleCopies SampleCopySlice `boil:"SampleCopies" json:"SampleCopies" toml:"SampleCopies" yaml:"SampleCopies"`
	Samples      SampleSlice     `boil:"Samples" json:"Samples" toml:"Samples" yaml:"Samples"`
	TreeSamples  TreeSampleSlice `boil:"TreeSamples" json:"TreeSamples" toml:"TreeSamples" yaml:"TreeSamples"`
}

// NewStruct creates a new relationship struct
func (*officeR) NewStruct() *officeR {
	return &officeR{}
}

// officeL is where Load methods for each relationship are stored.
type officeL struct{}

var (
	officeAllColumns            = []string{"id", "name"}
	officeColumnsWithoutDefault = []string{"id", "name"}
	officeColumnsWithDefault    = []string{}
	officePrimaryKeyColumns     = []string{"id"}
	officeGeneratedColumns      = []string{}
)

type (
	// OfficeSlice is an alias for a slice of pointers to Office.
	// This should almost always be used instead of []Office.
	OfficeSlice []*Office
	// OfficeHook is the signature for custom Office hook methods
	OfficeHook func(context.Context, boil.ContextExecutor, *Office) error

	officeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	officeType                 = reflect.TypeOf(&Office{})
	officeMapping              = queries.MakeStructMapping(officeType)
	officePrimaryKeyMapping, _ = queries.BindMapping(officeType, officeMapping, officePrimaryKeyColumns)
	officeInsertCacheMut       sync.RWMutex
	officeInsertCache          = make(map[string]insertCache)
	officeUpdateCacheMut       sync.RWMutex
	officeUpdateCache          = make(map[string]updateCache)
	officeUpsertCacheMut       sync.RWMutex
	officeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var officeAfterSelectHooks []OfficeHook

var officeBeforeInsertHooks []OfficeHook
var officeAfterInsertHooks []OfficeHook

var officeBeforeUpdateHooks []OfficeHook
var officeAfterUpdateHooks []OfficeHook

var officeBeforeDeleteHooks []OfficeHook
var officeAfterDeleteHooks []OfficeHook

var officeBeforeUpsertHooks []OfficeHook
var officeAfterUpsertHooks []OfficeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Office) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range officeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Office) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range officeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Office) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range officeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Office) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range officeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Office) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range officeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Office) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range officeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Office) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range officeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Office) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range officeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Office) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range officeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddOfficeHook registers your hook function for all future operations.
func AddOfficeHook(hookPoint boil.HookPoint, officeHook OfficeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		officeAfterSelectHooks = append(officeAfterSelectHooks, officeHook)
	case boil.BeforeInsertHook:
		officeBeforeInsertHooks = append(officeBeforeInsertHooks, officeHook)
	case boil.AfterInsertHook:
		officeAfterInsertHooks = append(officeAfterInsertHooks, officeHook)
	case boil.BeforeUpdateHook:
		officeBeforeUpdateHooks = append(officeBeforeUpdateHooks, officeHook)
	case boil.AfterUpdateHook:
		officeAfterUpdateHooks = append(officeAfterUpdateHooks, officeHook)
	case boil.BeforeDeleteHook:
		officeBeforeDeleteHooks = append(officeBeforeDeleteHooks, officeHook)
	case boil.AfterDeleteHook:
		officeAfterDeleteHooks = append(officeAfterDeleteHooks, officeHook)
	case boil.BeforeUpsertHook:
		officeBeforeUpsertHooks = append(officeBeforeUpsertHooks, officeHook)
	case boil.AfterUpsertHook:
		officeAfterUpsertHooks = append(officeAfterUpsertHooks, officeHook)
	}
}

// OneG returns a single office record from the query using the global executor.
func (q officeQuery) OneG(ctx context.Context) (*Office, error) {
	return q.One(ctx, boil.GetContextDB())
}

// OneGP returns a single office record from the query using the global executor, and panics on error.
func (q officeQuery) OneGP(ctx context.Context) *Office {
	o, err := q.One(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// OneP returns a single office record from the query, and panics on error.
func (q officeQuery) OneP(ctx context.Context, exec boil.ContextExecutor) *Office {
	o, err := q.One(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single office record from the query.
func (q officeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Office, error) {
	o := &Office{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for offices")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Office records from the query using the global executor.
func (q officeQuery) AllG(ctx context.Context) (OfficeSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// AllGP returns all Office records from the query using the global executor, and panics on error.
func (q officeQuery) AllGP(ctx context.Context) OfficeSlice {
	o, err := q.All(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// AllP returns all Office records from the query, and panics on error.
func (q officeQuery) AllP(ctx context.Context, exec boil.ContextExecutor) OfficeSlice {
	o, err := q.All(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Office records from the query.
func (q officeQuery) All(ctx context.Context, exec boil.ContextExecutor) (OfficeSlice, error) {
	var o []*Office

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Office slice")
	}

	if len(officeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Office records in the query using the global executor
func (q officeQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// CountGP returns the count of all Office records in the query using the global executor, and panics on error.
func (q officeQuery) CountGP(ctx context.Context) int64 {
	c, err := q.Count(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// CountP returns the count of all Office records in the query, and panics on error.
func (q officeQuery) CountP(ctx context.Context, exec boil.ContextExecutor) int64 {
	c, err := q.Count(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Office records in the query.
func (q officeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count offices rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q officeQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// ExistsGP checks if the row exists in the table using the global executor, and panics on error.
func (q officeQuery) ExistsGP(ctx context.Context) bool {
	e, err := q.Exists(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ExistsP checks if the row exists in the table, and panics on error.
func (q officeQuery) ExistsP(ctx context.Context, exec boil.ContextExecutor) bool {
	e, err := q.Exists(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q officeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if offices exists")
	}

	return count > 0, nil
}

// OfficeUsers retrieves all the office_user's OfficeUsers with an executor.
func (o *Office) OfficeUsers(mods ...qm.QueryMod) officeUserQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`office_users`.`office_id`=?", o.ID),
	)

	query := OfficeUsers(queryMods...)
	queries.SetFrom(query.Query, "`office_users`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`office_users`.*"})
	}

	return query
}

// SampleCopies retrieves all the sample_copy's SampleCopies with an executor.
func (o *Office) SampleCopies(mods ...qm.QueryMod) sampleCopyQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`sample_copies`.`office_id`=?", o.ID),
	)

	query := SampleCopies(queryMods...)
	queries.SetFrom(query.Query, "`sample_copies`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`sample_copies`.*"})
	}

	return query
}

// Samples retrieves all the sample's Samples with an executor.
func (o *Office) Samples(mods ...qm.QueryMod) sampleQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`samples`.`office_id`=?", o.ID),
	)

	query := Samples(queryMods...)
	queries.SetFrom(query.Query, "`samples`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`samples`.*"})
	}

	return query
}

// TreeSamples retrieves all the tree_sample's TreeSamples with an executor.
func (o *Office) TreeSamples(mods ...qm.QueryMod) treeSampleQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`tree_samples`.`office_id`=?", o.ID),
	)

	query := TreeSamples(queryMods...)
	queries.SetFrom(query.Query, "`tree_samples`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`tree_samples`.*"})
	}

	return query
}

// LoadOfficeUsers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (officeL) LoadOfficeUsers(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOffice interface{}, mods queries.Applicator) error {
	var slice []*Office
	var object *Office

	if singular {
		object = maybeOffice.(*Office)
	} else {
		slice = *maybeOffice.(*[]*Office)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &officeR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &officeR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`office_users`),
		qm.WhereIn(`office_users.office_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load office_users")
	}

	var resultSlice []*OfficeUser
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice office_users")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on office_users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for office_users")
	}

	if len(officeUserAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.OfficeUsers = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &officeUserR{}
			}
			foreign.R.Office = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.OfficeID {
				local.R.OfficeUsers = append(local.R.OfficeUsers, foreign)
				if foreign.R == nil {
					foreign.R = &officeUserR{}
				}
				foreign.R.Office = local
				break
			}
		}
	}

	return nil
}

// LoadSampleCopies allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (officeL) LoadSampleCopies(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOffice interface{}, mods queries.Applicator) error {
	var slice []*Office
	var object *Office

	if singular {
		object = maybeOffice.(*Office)
	} else {
		slice = *maybeOffice.(*[]*Office)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &officeR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &officeR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`sample_copies`),
		qm.WhereIn(`sample_copies.office_id in ?`, args...),
		qmhelper.WhereIsNull(`sample_copies.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load sample_copies")
	}

	var resultSlice []*SampleCopy
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice sample_copies")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on sample_copies")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for sample_copies")
	}

	if len(sampleCopyAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SampleCopies = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &sampleCopyR{}
			}
			foreign.R.Office = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.OfficeID {
				local.R.SampleCopies = append(local.R.SampleCopies, foreign)
				if foreign.R == nil {
					foreign.R = &sampleCopyR{}
				}
				foreign.R.Office = local
				break
			}
		}
	}

	return nil
}

// LoadSamples allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (officeL) LoadSamples(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOffice interface{}, mods queries.Applicator) error {
	var slice []*Office
	var object *Office

	if singular {
		object = maybeOffice.(*Office)
	} else {
		slice = *maybeOffice.(*[]*Office)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &officeR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &officeR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`samples`),
		qm.WhereIn(`samples.office_id in ?`, args...),
		qmhelper.WhereIsNull(`samples.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load samples")
	}

	var resultSlice []*Sample
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice samples")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on samples")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for samples")
	}

	if len(sampleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Samples = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &sampleR{}
			}
			foreign.R.Office = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.OfficeID {
				local.R.Samples = append(local.R.Samples, foreign)
				if foreign.R == nil {
					foreign.R = &sampleR{}
				}
				foreign.R.Office = local
				break
			}
		}
	}

	return nil
}

// LoadTreeSamples allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (officeL) LoadTreeSamples(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOffice interface{}, mods queries.Applicator) error {
	var slice []*Office
	var object *Office

	if singular {
		object = maybeOffice.(*Office)
	} else {
		slice = *maybeOffice.(*[]*Office)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &officeR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &officeR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`tree_samples`),
		qm.WhereIn(`tree_samples.office_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load tree_samples")
	}

	var resultSlice []*TreeSample
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice tree_samples")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on tree_samples")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tree_samples")
	}

	if len(treeSampleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.TreeSamples = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &treeSampleR{}
			}
			foreign.R.Office = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.OfficeID {
				local.R.TreeSamples = append(local.R.TreeSamples, foreign)
				if foreign.R == nil {
					foreign.R = &treeSampleR{}
				}
				foreign.R.Office = local
				break
			}
		}
	}

	return nil
}

// AddOfficeUsersG adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.OfficeUsers.
// Sets related.R.Office appropriately.
// Uses the global database handle.
func (o *Office) AddOfficeUsersG(ctx context.Context, insert bool, related ...*OfficeUser) error {
	return o.AddOfficeUsers(ctx, boil.GetContextDB(), insert, related...)
}

// AddOfficeUsersP adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.OfficeUsers.
// Sets related.R.Office appropriately.
// Panics on error.
func (o *Office) AddOfficeUsersP(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*OfficeUser) {
	if err := o.AddOfficeUsers(ctx, exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddOfficeUsersGP adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.OfficeUsers.
// Sets related.R.Office appropriately.
// Uses the global database handle and panics on error.
func (o *Office) AddOfficeUsersGP(ctx context.Context, insert bool, related ...*OfficeUser) {
	if err := o.AddOfficeUsers(ctx, boil.GetContextDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddOfficeUsers adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.OfficeUsers.
// Sets related.R.Office appropriately.
func (o *Office) AddOfficeUsers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*OfficeUser) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.OfficeID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `office_users` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"office_id"}),
				strmangle.WhereClause("`", "`", 0, officeUserPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.OfficeID = o.ID
		}
	}

	if o.R == nil {
		o.R = &officeR{
			OfficeUsers: related,
		}
	} else {
		o.R.OfficeUsers = append(o.R.OfficeUsers, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &officeUserR{
				Office: o,
			}
		} else {
			rel.R.Office = o
		}
	}
	return nil
}

// AddSampleCopiesG adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.SampleCopies.
// Sets related.R.Office appropriately.
// Uses the global database handle.
func (o *Office) AddSampleCopiesG(ctx context.Context, insert bool, related ...*SampleCopy) error {
	return o.AddSampleCopies(ctx, boil.GetContextDB(), insert, related...)
}

// AddSampleCopiesP adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.SampleCopies.
// Sets related.R.Office appropriately.
// Panics on error.
func (o *Office) AddSampleCopiesP(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*SampleCopy) {
	if err := o.AddSampleCopies(ctx, exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddSampleCopiesGP adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.SampleCopies.
// Sets related.R.Office appropriately.
// Uses the global database handle and panics on error.
func (o *Office) AddSampleCopiesGP(ctx context.Context, insert bool, related ...*SampleCopy) {
	if err := o.AddSampleCopies(ctx, boil.GetContextDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddSampleCopies adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.SampleCopies.
// Sets related.R.Office appropriately.
func (o *Office) AddSampleCopies(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*SampleCopy) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.OfficeID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `sample_copies` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"office_id"}),
				strmangle.WhereClause("`", "`", 0, sampleCopyPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.OfficeID = o.ID
		}
	}

	if o.R == nil {
		o.R = &officeR{
			SampleCopies: related,
		}
	} else {
		o.R.SampleCopies = append(o.R.SampleCopies, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &sampleCopyR{
				Office: o,
			}
		} else {
			rel.R.Office = o
		}
	}
	return nil
}

// AddSamplesG adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.Samples.
// Sets related.R.Office appropriately.
// Uses the global database handle.
func (o *Office) AddSamplesG(ctx context.Context, insert bool, related ...*Sample) error {
	return o.AddSamples(ctx, boil.GetContextDB(), insert, related...)
}

// AddSamplesP adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.Samples.
// Sets related.R.Office appropriately.
// Panics on error.
func (o *Office) AddSamplesP(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Sample) {
	if err := o.AddSamples(ctx, exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddSamplesGP adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.Samples.
// Sets related.R.Office appropriately.
// Uses the global database handle and panics on error.
func (o *Office) AddSamplesGP(ctx context.Context, insert bool, related ...*Sample) {
	if err := o.AddSamples(ctx, boil.GetContextDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddSamples adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.Samples.
// Sets related.R.Office appropriately.
func (o *Office) AddSamples(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Sample) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.OfficeID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `samples` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"office_id"}),
				strmangle.WhereClause("`", "`", 0, samplePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.OfficeID = o.ID
		}
	}

	if o.R == nil {
		o.R = &officeR{
			Samples: related,
		}
	} else {
		o.R.Samples = append(o.R.Samples, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &sampleR{
				Office: o,
			}
		} else {
			rel.R.Office = o
		}
	}
	return nil
}

// AddTreeSamplesG adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.TreeSamples.
// Sets related.R.Office appropriately.
// Uses the global database handle.
func (o *Office) AddTreeSamplesG(ctx context.Context, insert bool, related ...*TreeSample) error {
	return o.AddTreeSamples(ctx, boil.GetContextDB(), insert, related...)
}

// AddTreeSamplesP adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.TreeSamples.
// Sets related.R.Office appropriately.
// Panics on error.
func (o *Office) AddTreeSamplesP(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TreeSample) {
	if err := o.AddTreeSamples(ctx, exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTreeSamplesGP adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.TreeSamples.
// Sets related.R.Office appropriately.
// Uses the global database handle and panics on error.
func (o *Office) AddTreeSamplesGP(ctx context.Context, insert bool, related ...*TreeSample) {
	if err := o.AddTreeSamples(ctx, boil.GetContextDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTreeSamples adds the given related objects to the existing relationships
// of the office, optionally inserting them as new records.
// Appends related to o.R.TreeSamples.
// Sets related.R.Office appropriately.
func (o *Office) AddTreeSamples(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TreeSample) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.OfficeID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `tree_samples` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"office_id"}),
				strmangle.WhereClause("`", "`", 0, treeSamplePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.OfficeID = o.ID
		}
	}

	if o.R == nil {
		o.R = &officeR{
			TreeSamples: related,
		}
	} else {
		o.R.TreeSamples = append(o.R.TreeSamples, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &treeSampleR{
				Office: o,
			}
		} else {
			rel.R.Office = o
		}
	}
	return nil
}

// Offices retrieves all the records using an executor.
func Offices(mods ...qm.QueryMod) officeQuery {
	mods = append(mods, qm.From("`offices`"))
	return officeQuery{NewQuery(mods...)}
}

// FindOfficeG retrieves a single record by ID.
func FindOfficeG(ctx context.Context, iD string, selectCols ...string) (*Office, error) {
	return FindOffice(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindOfficeP retrieves a single record by ID with an executor, and panics on error.
func FindOfficeP(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) *Office {
	retobj, err := FindOffice(ctx, exec, iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindOfficeGP retrieves a single record by ID, and panics on error.
func FindOfficeGP(ctx context.Context, iD string, selectCols ...string) *Office {
	retobj, err := FindOffice(ctx, boil.GetContextDB(), iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindOffice retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindOffice(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Office, error) {
	officeObj := &Office{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `offices` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, officeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from offices")
	}

	if err = officeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return officeObj, err
	}

	return officeObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Office) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Office) InsertP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) {
	if err := o.Insert(ctx, exec, columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Office) InsertGP(ctx context.Context, columns boil.Columns) {
	if err := o.Insert(ctx, boil.GetContextDB(), columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Office) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no offices provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(officeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	officeInsertCacheMut.RLock()
	cache, cached := officeInsertCache[key]
	officeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			officeAllColumns,
			officeColumnsWithDefault,
			officeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(officeType, officeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(officeType, officeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `offices` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `offices` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `offices` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, officePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into offices")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for offices")
	}

CacheNoHooks:
	if !cached {
		officeInsertCacheMut.Lock()
		officeInsertCache[key] = cache
		officeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Office record using the global executor.
// See Update for more documentation.
func (o *Office) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// UpdateP uses an executor to update the Office, and panics on error.
// See Update for more documentation.
func (o *Office) UpdateP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, exec, columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateGP a single Office record using the global executor. Panics on error.
// See Update for more documentation.
func (o *Office) UpdateGP(ctx context.Context, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, boil.GetContextDB(), columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Update uses an executor to update the Office.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Office) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	officeUpdateCacheMut.RLock()
	cache, cached := officeUpdateCache[key]
	officeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			officeAllColumns,
			officePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update offices, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `offices` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, officePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(officeType, officeMapping, append(wl, officePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update offices row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for offices")
	}

	if !cached {
		officeUpdateCacheMut.Lock()
		officeUpdateCache[key] = cache
		officeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q officeQuery) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllG updates all rows with the specified column values.
func (q officeQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (q officeQuery) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values.
func (q officeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for offices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for offices")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o OfficeSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o OfficeSlice) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o OfficeSlice) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o OfficeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), officePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `offices` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, officePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in office slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all office")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Office) UpsertG(ctx context.Context, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateColumns, insertColumns)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Office) UpsertGP(ctx context.Context, updateColumns, insertColumns boil.Columns) {
	if err := o.Upsert(ctx, boil.GetContextDB(), updateColumns, insertColumns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Office) UpsertP(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) {
	if err := o.Upsert(ctx, exec, updateColumns, insertColumns); err != nil {
		panic(boil.WrapErr(err))
	}
}

var mySQLOfficeUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Office) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no offices provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(officeColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLOfficeUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	officeUpsertCacheMut.RLock()
	cache, cached := officeUpsertCache[key]
	officeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			officeAllColumns,
			officeColumnsWithDefault,
			officeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			officeAllColumns,
			officePrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert offices, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`offices`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `offices` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(officeType, officeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(officeType, officeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for offices")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(officeType, officeMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for offices")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for offices")
	}

CacheNoHooks:
	if !cached {
		officeUpsertCacheMut.Lock()
		officeUpsertCache[key] = cache
		officeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Office record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Office) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// DeleteP deletes a single Office record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Office) DeleteP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := o.Delete(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteGP deletes a single Office record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Office) DeleteGP(ctx context.Context) int64 {
	rowsAff, err := o.Delete(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Delete deletes a single Office record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Office) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Office provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), officePrimaryKeyMapping)
	sql := "DELETE FROM `offices` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from offices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for offices")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q officeQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAllP deletes all rows, and panics on error.
func (q officeQuery) DeleteAllP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := q.DeleteAll(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows, and panics on error.
func (q officeQuery) DeleteAllGP(ctx context.Context) int64 {
	rowsAff, err := q.DeleteAll(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all matching rows.
func (q officeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no officeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from offices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for offices")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o OfficeSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o OfficeSlice) DeleteAllP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := o.DeleteAll(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o OfficeSlice) DeleteAllGP(ctx context.Context) int64 {
	rowsAff, err := o.DeleteAll(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o OfficeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(officeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), officePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `offices` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, officePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from office slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for offices")
	}

	if len(officeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Office) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no Office provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Office) ReloadP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.Reload(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Office) ReloadGP(ctx context.Context) {
	if err := o.Reload(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Office) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindOffice(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OfficeSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty OfficeSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *OfficeSlice) ReloadAllP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.ReloadAll(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *OfficeSlice) ReloadAllGP(ctx context.Context) {
	if err := o.ReloadAll(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OfficeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := OfficeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), officePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `offices`.* FROM `offices` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, officePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in OfficeSlice")
	}

	*o = slice

	return nil
}

// OfficeExistsG checks if the Office row exists.
func OfficeExistsG(ctx context.Context, iD string) (bool, error) {
	return OfficeExists(ctx, boil.GetContextDB(), iD)
}

// OfficeExistsP checks if the Office row exists. Panics on error.
func OfficeExistsP(ctx context.Context, exec boil.ContextExecutor, iD string) bool {
	e, err := OfficeExists(ctx, exec, iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// OfficeExistsGP checks if the Office row exists. Panics on error.
func OfficeExistsGP(ctx context.Context, iD string) bool {
	e, err := OfficeExists(ctx, boil.GetContextDB(), iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// OfficeExists checks if the Office row exists.
func OfficeExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `offices` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if offices exists")
	}

	return exists, nil
}
